- name: Instalando o pip
  apt:
    name:
      - python-pip

- name: Instalando dependencias do modulo k8s
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiando o arquivo de deployment da app V1
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deployment da app v2
  template:
    src: app-v2.yml.j2
    dest: /opt/giropops/app-v2.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v2
    
- name: Deploy da app v2 #modulo k8s, mesma coisa que o apply
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v2.yml

- name: Scale down app-v1 #diminuir replicas/pods da primeira
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v1.yml

- name: Dentro de 02 minutos a app-v1 sera removida. Pressione control+c para cancelar.
  pause:
    minutes: 2

- name: Removendo a App-V1
  k8s:
    state: absent
    namespace: default
    src: /opt/giropops/app-v1.yml